"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConnectKitModalDemo = exports.useChainIsSupported = exports.useChains = exports.useIsMounted = exports.ChainIcon = exports.Avatar = exports.SIWEButton = exports.ConnectKitButton = exports.Context = exports.ConnectKitProvider = exports.useModal = exports.wallets = exports.getDefaultConnectors = exports.getDefaultConfig = exports.Types = exports.CONNECTKIT_VERSION = void 0;
exports.CONNECTKIT_VERSION = '1.7.1';
exports.Types = require("./types");
var defaultConfig_1 = require("./defaultConfig");
Object.defineProperty(exports, "getDefaultConfig", { enumerable: true, get: function () { return defaultConfig_1.default; } });
var defaultConnectors_1 = require("./defaultConnectors");
Object.defineProperty(exports, "getDefaultConnectors", { enumerable: true, get: function () { return defaultConnectors_1.default; } });
var wallets_1 = require("./wallets");
Object.defineProperty(exports, "wallets", { enumerable: true, get: function () { return wallets_1.wallets; } });
var useModal_1 = require("./hooks/useModal");
Object.defineProperty(exports, "useModal", { enumerable: true, get: function () { return useModal_1.useModal; } });
var ConnectKit_1 = require("./components/ConnectKit");
Object.defineProperty(exports, "ConnectKitProvider", { enumerable: true, get: function () { return ConnectKit_1.ConnectKitProvider; } });
Object.defineProperty(exports, "Context", { enumerable: true, get: function () { return ConnectKit_1.Context; } });
var ConnectButton_1 = require("./components/ConnectButton");
Object.defineProperty(exports, "ConnectKitButton", { enumerable: true, get: function () { return ConnectButton_1.ConnectKitButton; } });
var SIWE_1 = require("./components/Standard/SIWE");
Object.defineProperty(exports, "SIWEButton", { enumerable: true, get: function () { return SIWE_1.default; } });
var Avatar_1 = require("./components/Common/Avatar");
Object.defineProperty(exports, "Avatar", { enumerable: true, get: function () { return Avatar_1.default; } });
var Chain_1 = require("./components/Common/Chain");
Object.defineProperty(exports, "ChainIcon", { enumerable: true, get: function () { return Chain_1.default; } });
var useIsMounted_1 = require("./hooks/useIsMounted");
Object.defineProperty(exports, "useIsMounted", { enumerable: true, get: function () { return useIsMounted_1.default; } });
var useChains_1 = require("./hooks/useChains");
Object.defineProperty(exports, "useChains", { enumerable: true, get: function () { return useChains_1.useChains; } });
var useChainIsSupported_1 = require("./hooks/useChainIsSupported");
Object.defineProperty(exports, "useChainIsSupported", { enumerable: true, get: function () { return useChainIsSupported_1.useChainIsSupported; } });
var demo_1 = require("./components/ConnectModal/demo");
Object.defineProperty(exports, "ConnectKitModalDemo", { enumerable: true, get: function () { return demo_1.default; } });
//# sourceMappingURL=index.js.map